- id: '1583552499746'
  alias: Living Room Lights - On
  description: Turn living room lights on.
  trigger:
  - platform: numeric_state
    entity_id: sensor.living_room_light_level
    below: '13000'
  condition:
  - condition: sun
    after: sunset
    after_offset: -01:30:00
  action:
  - service: script.livingroomlights
    data: {}
  mode: restart
- id: '1583614877368'
  alias: Garage Light On
  description: Turn lights on when garage door open
  trigger:
  - entity_id: cover.garage_door
    platform: state
    to: open
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 255
    entity_id: light.garage
  mode: restart
- id: '1583614954065'
  alias: Garage Light Off
  description: Turn lights off when Garage door closed
  trigger:
  - entity_id: cover.garage_door
    platform: state
    to: closed
  condition:
  - condition: state
    entity_id: light.garage
    state: 'on'
  action:
  - service: light.turn_off
    data:
      transition: 10
    entity_id: light.garage
  mode: restart
- id: '1584893464573'
  alias: Living Room Lights - Off
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    service: script.transition_living_room_lights_off
  mode: restart
- id: '1587261294860'
  alias: Close Garage Door
  description: Close garage door when alarm set to home or away
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ring_alarm
    to: armed_home
  condition:
  - condition: state
    entity_id: cover.garage_door
    state: open
  action:
  - data: {}
    entity_id: cover.garage_door
    service: cover.close_cover
  mode: restart
- id: '1593321973249'
  alias: Outside Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:15:00
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.outdoor_lights
  mode: restart
- id: '1596602195449'
  alias: Outside lights off
  description: Turn outside lights off when alarm is set to home
  trigger:
  - platform: template
    value_template: '{{ is_state(''alarm_control_panel.ring_alarm'', ''armed_home'')
      }}'
  condition: []
  action:
  - delay: 00:15:00
  - service: light.turn_off
    data: {}
    entity_id: light.outdoor_lights
  mode: restart
- id: '1604878126809'
  alias: Bedroom Lamp - On
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: script.bedroom
    data: {}
  mode: single
- id: '1604878498749'
  alias: Bedroom Lamp - Off
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 5
    entity_id: light.hue_color_lamp_4
  mode: single
- id: '1609195530820'
  alias: Living room lights off after 10 minutes
  description: Turn off living room lights off 10 minutes after last movement if on
    after 11pm.
  trigger:
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_1_motion
    to: 'off'
    for: 00:10:00
  condition:
  - condition: time
    after: '23:30'
  action:
  - service: script.transition_living_room_lights_off
    data: {}
  mode: restart
- id: '1611716087928'
  alias: Bar Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.switch1
  mode: restart
