- id: '1583552499746'
  alias: Living Room Lights - On
  description: Turn living room lights on.
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  condition:
  - condition: template
    value_template: '{{ states.sensor.hue_motion_sensor_1_light_level.attributes.lightlevel  |
      int < 14000 }}'
  action:
  - service: script.livingroomlights
    data: {}
  mode: restart
- id: '1583614877368'
  alias: Garage Light On
  description: Turn lights on when garage door open
  trigger:
  - entity_id: cover.garage_door
    platform: state
    to: open
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - service: light.turn_on
    data:
      brightness: 255
    entity_id: light.garage
  mode: restart
- id: '1583614954065'
  alias: Garage Light Off
  description: Turn lights off when Garage door closed
  trigger:
  - entity_id: cover.garage_door
    platform: state
    to: closed
  condition:
  - condition: state
    entity_id: light.garage
    state: 'on'
  action:
  - service: light.turn_off
    data:
      transition: 10
    entity_id: light.garage
  mode: restart
- id: '1584893464573'
  alias: Living Room Lights - Off
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    service: script.transition_living_room_lights_off
  mode: restart
- id: '1587261294860'
  alias: Close Garage Door
  description: Close garage door when alarm set to home or away
  trigger:
  - platform: template
    value_template: '{{ is_state(''alarm_control_panel.ring_alarm'', ''armed_home'')
      }}'
  condition:
  - condition: state
    entity_id: cover.garage_door
    state: open
  action:
  - data: {}
    entity_id: cover.garage_door
    service: cover.close_cover
  mode: single
- id: '1593321973249'
  alias: Outside Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:10:00
  condition: []
  action:
  - scene: scene.outside_lights_on
  mode: restart
- id: '1596602195449'
  alias: Outside lights off
  description: Turn outside lights off when alarm is set to home
  trigger:
  - platform: template
    value_template: '{{ is_state(''alarm_control_panel.ring_alarm'', ''armed_home'')
      }}'
  condition: []
  action:
  - delay: 00:15:00
  - scene: scene.outside_lights_off
  - service: light.turn_off
    data: {}
    entity_id: light.hue_white_lamp_1
  mode: restart
- id: '1604878126809'
  alias: Bedroom Lamp - On
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: script.bedroom
    data: {}
  mode: single
- id: '1604878498749'
  alias: Bedroom Lamp - Off
  description: ''
  trigger:
  - platform: time
    at: '23:30:00'
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 5
    entity_id: light.hue_color_lamp_4
  mode: single
- id: '1604879778228'
  alias: Xmas Tree - Off
  description: ''
  trigger:
  - platform: time
    at: '23:30:00'
  condition: []
  action:
  - scene: scene.xmas_lights_off
  mode: single
- id: '1604879928786'
  alias: Xmas Lights - On
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - scene: scene.xmas_lights_on
  mode: single
