homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 43.6403
  longitude: -79.3711
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 176
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  # Duck DNS & Let's Encrypt
  internal_url: !secret internal_url
  external_url: !secret external_url
  # Customization file
  customize: !include customize.yaml

http:
  server_port: 8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
ios:

frontend:
  themes: !include_dir_merge_named themes

# menubar stuff
hassio:

  # Stream
stream:

# Nest
nest:
  client_id: !secret client_id
  client_secret: !secret client_secret
  project_id: !secret project_id
  subscriber_id: !secret subscriber_id

# outdoor cameras
camera:
  - platform: mjpeg
    mjpeg_url: !secret backyard_mjpeg_url
    still_image_url: !secret backyard_still_image_url
    name: Backyard
    authentication: basic
    username: !secret backyard_camera_user
    password: !secret backyard_camera_password

  - platform: mjpeg
    mjpeg_url: !secret garage_mjpeg_url
    still_image_url: !secret garage_still_image_url
    name: Garage
    authentication: basic
    username: !secret garage_camera_user
    password: !secret garage_camera_password

# System Health
system_health:

# Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
light: !include light_group.yaml
scene: !include scenes.yaml
