# sensors

# Host
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: swap_use_percent
    - type: last_boot

# Badnest
- platform: badnest

# Door sensors
- platform: template
  sensors:
    front_door_sensor_battery_level:
      friendly_name: "Front Door Sensor Battery Level"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('binary_sensor.front_door', 'battery_level') }}"
    back_door_sensor_battery_level:
      friendly_name: "Back Door Sensor Battery Level"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('binary_sensor.back_door', 'battery_level') }}"
    motion_sensor_battery_level:
      friendly_name: "Motion Sensor Battery Level"
      unit_of_measurement: '%'
      value_template: "{{ states.binary_sensor.hue_motion_sensor_1_motion.attributes.battery_level }}"
